-- CreateTable
CREATE TABLE "Player" (
    "PId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Session" (
    "SId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CreationDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "StartTime" DATETIME NOT NULL,
    "EndTime" DATETIME NOT NULL,
    "PlayerId" INTEGER NOT NULL,
    CONSTRAINT "Session_PlayerId_fkey" FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PId") ON DELETE RESTRICT ON UPDATE CASCADE
);
