version: "3.8"
services:
  frontend-dev:
    image: frontend-prod
    build:
      context: .
      dockerfile: DockerFile.prod
    ports:
      - "5173:5173"
    environment:
      - VITE_API_HOST_URL=http://localhost:5000
    command: ["npm", "run", "preview"]