services:
  frontend-prod:
    image: ghcr.io/krisvan/pickleball-scheduler/frontend-prod:20250508v2
    container_name: frontend-prod
    build:
      context: .
      dockerfile: DockerFile.prod
    ports:
      - "5173:5173"
    environment:
      - VITE_API_HOST_URL=http://localhost:5000
    command: ["npm", "run", "preview"]