services:
  frontend-prod:
    image: ghcr.io/krisvan/pickleball-scheduler/frontend:20250508v3
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_HOST_URL=http://localhost:5000
    command: ["npm", "run", "preview"]