# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
jobs:
  build_test: 
    executor: node/default
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Download CI dependency
          command: npm ci
      - run:
          name: Start app
          command: npm run start
          background: true
      - run:
          command: npm run lint
          name: Enforce code styles
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_test_workflow:
    jobs:
      - build_test
