# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    steps: 
      - attach_workspace:
          at: .
      - run:
        command: npm run deploy
        name: Deploy app


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
        requires:
          - build_and_test # Only deploy if build and test succesful
        # filters:
        #   branches:
        #     only: main # Only deploy when on main branch
